Repository UNIZAR-30226-2025-11/backend, pull requests merged in 2025-03, with the labels that each got.

#20 Fixed Compose on Windows
  .env.database.example
  .env.example
  .gitignore
  README.md
  docker/docker-compose.yml
  sql/init.sql
  src/index.ts
Labels: enhancement

#29 Communication with Sockets implement
  src/services/communication/communicationHandler.ts
  src/services/communication/socketCommunicationHandler.ts
Labels: development

#30 Repositories
  src/repositories/gameRepository.ts
  src/repositories/lobbyRepository.ts
Labels: development

#31 Added explicit URL for CORS
  .env.example
  src/app.ts
  src/config.ts
  src/index.ts
  src/users/middleware.ts
  src/users/routes.ts
  test/users.test.ts
Labels: bug
